export const FETCH_ITEMS = 'FETCH_ITEMS'
export const SHOW_ITEM = 'SHOW_ITEM'
export const ADD_TO_CART = 'ADD_TO_CART'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_REMOVE = 'HANDLE_REMOVE'
